// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCERn8vio1mx-DxjcFhOT4_SGYqB9kB4wg',
    appId: '1:948882574304:web:f9a6e7584373066538b985',
    messagingSenderId: '948882574304',
    projectId: 'doctor-app-c666b',
    authDomain: 'doctor-app-c666b.firebaseapp.com',
    storageBucket: 'doctor-app-c666b.firebasestorage.app',
    measurementId: 'G-FPG0RQJK7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNEq3P_tw7Xi6nFaKqDq2yvQlvFNFG9SQ',
    appId: '1:948882574304:android:c3164472d1ae153838b985',
    messagingSenderId: '948882574304',
    projectId: 'doctor-app-c666b',
    storageBucket: 'doctor-app-c666b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChfoD0NqHl4m1aitfavyY3ni_Zr03rcLc',
    appId: '1:948882574304:ios:730e7543b7d6222638b985',
    messagingSenderId: '948882574304',
    projectId: 'doctor-app-c666b',
    storageBucket: 'doctor-app-c666b.firebasestorage.app',
    iosBundleId: 'com.example.blocPatron',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChfoD0NqHl4m1aitfavyY3ni_Zr03rcLc',
    appId: '1:948882574304:ios:730e7543b7d6222638b985',
    messagingSenderId: '948882574304',
    projectId: 'doctor-app-c666b',
    storageBucket: 'doctor-app-c666b.firebasestorage.app',
    iosBundleId: 'com.example.blocPatron',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCERn8vio1mx-DxjcFhOT4_SGYqB9kB4wg',
    appId: '1:948882574304:web:2906f91bc8ee277b38b985',
    messagingSenderId: '948882574304',
    projectId: 'doctor-app-c666b',
    authDomain: 'doctor-app-c666b.firebaseapp.com',
    storageBucket: 'doctor-app-c666b.firebasestorage.app',
    measurementId: 'G-0RDQ482XE8',
  );
}
